### ISSUE TITLE
rm duplicate repo from Atmosphere

### ISSUE THREAD

**Issue by dandv** [416serg/onboard#1]
Hi,

Thanks for following my template for wrapper packages. I see there are two for onboard,

https://atmospherejs.com/416serg/onboard
https://atmospherejs.com/416serg/onboardjs

The second has a broken GitHub link so maybe remove it?

```
meteor admin set-unmigrated 416serg:onboardjs
```

**Comment by sergical** [comment]
apologies for missing this... it's removed now
